name: CI

on:
  push:
    branches:
      - main
      - development
      - release
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest -p no:cacheprovider

    - name: Install Doxygen
      run: |
        sudo apt update
        sudo apt install doxygen

    - name: Generate documentation
      run: |
        mkdir -p docs/html
        doxygen Doxyfile